// flow-typed signature: 7d34b7311a5da3a6fe3b242a2f1cc85f
// flow-typed version: <<STUB>>/@formatjs/cli_v^4.5.0/flow_v0.168.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@formatjs/cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@formatjs/cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@formatjs/cli/src/cli' {
  declare module.exports: any;
}

declare module '@formatjs/cli/src/compile_folder' {
  declare module.exports: any;
}

declare module '@formatjs/cli/src/compile' {
  declare module.exports: any;
}

declare module '@formatjs/cli/src/console_utils' {
  declare module.exports: any;
}

declare module '@formatjs/cli/src/extract' {
  declare module.exports: any;
}

declare module '@formatjs/cli/src/formatters/crowdin' {
  declare module.exports: any;
}

declare module '@formatjs/cli/src/formatters/default' {
  declare module.exports: any;
}

declare module '@formatjs/cli/src/formatters' {
  declare module.exports: any;
}

declare module '@formatjs/cli/src/formatters/lokalise' {
  declare module.exports: any;
}

declare module '@formatjs/cli/src/formatters/simple' {
  declare module.exports: any;
}

declare module '@formatjs/cli/src/formatters/smartling' {
  declare module.exports: any;
}

declare module '@formatjs/cli/src/formatters/transifex' {
  declare module.exports: any;
}

declare module '@formatjs/cli/src/parse_script' {
  declare module.exports: any;
}

declare module '@formatjs/cli/src/pseudo_locale' {
  declare module.exports: any;
}

declare module '@formatjs/cli/src/vue_extractor' {
  declare module.exports: any;
}

// Filename aliases
declare module '@formatjs/cli/index' {
  declare module.exports: $Exports<'@formatjs/cli'>;
}
declare module '@formatjs/cli/index.js' {
  declare module.exports: $Exports<'@formatjs/cli'>;
}
declare module '@formatjs/cli/src/cli.js' {
  declare module.exports: $Exports<'@formatjs/cli/src/cli'>;
}
declare module '@formatjs/cli/src/compile_folder.js' {
  declare module.exports: $Exports<'@formatjs/cli/src/compile_folder'>;
}
declare module '@formatjs/cli/src/compile.js' {
  declare module.exports: $Exports<'@formatjs/cli/src/compile'>;
}
declare module '@formatjs/cli/src/console_utils.js' {
  declare module.exports: $Exports<'@formatjs/cli/src/console_utils'>;
}
declare module '@formatjs/cli/src/extract.js' {
  declare module.exports: $Exports<'@formatjs/cli/src/extract'>;
}
declare module '@formatjs/cli/src/formatters/crowdin.js' {
  declare module.exports: $Exports<'@formatjs/cli/src/formatters/crowdin'>;
}
declare module '@formatjs/cli/src/formatters/default.js' {
  declare module.exports: $Exports<'@formatjs/cli/src/formatters/default'>;
}
declare module '@formatjs/cli/src/formatters/index' {
  declare module.exports: $Exports<'@formatjs/cli/src/formatters'>;
}
declare module '@formatjs/cli/src/formatters/index.js' {
  declare module.exports: $Exports<'@formatjs/cli/src/formatters'>;
}
declare module '@formatjs/cli/src/formatters/lokalise.js' {
  declare module.exports: $Exports<'@formatjs/cli/src/formatters/lokalise'>;
}
declare module '@formatjs/cli/src/formatters/simple.js' {
  declare module.exports: $Exports<'@formatjs/cli/src/formatters/simple'>;
}
declare module '@formatjs/cli/src/formatters/smartling.js' {
  declare module.exports: $Exports<'@formatjs/cli/src/formatters/smartling'>;
}
declare module '@formatjs/cli/src/formatters/transifex.js' {
  declare module.exports: $Exports<'@formatjs/cli/src/formatters/transifex'>;
}
declare module '@formatjs/cli/src/parse_script.js' {
  declare module.exports: $Exports<'@formatjs/cli/src/parse_script'>;
}
declare module '@formatjs/cli/src/pseudo_locale.js' {
  declare module.exports: $Exports<'@formatjs/cli/src/pseudo_locale'>;
}
declare module '@formatjs/cli/src/vue_extractor.js' {
  declare module.exports: $Exports<'@formatjs/cli/src/vue_extractor'>;
}
