// flow-typed signature: c7f998311e5bc6b872f70cc69b3e5162
// flow-typed version: <<STUB>>/babel-plugin-formatjs_v^10.3.12/flow_v0.168.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-formatjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-formatjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-formatjs/types' {
  declare module.exports: any;
}

declare module 'babel-plugin-formatjs/utils' {
  declare module.exports: any;
}

declare module 'babel-plugin-formatjs/visitors/call-expression' {
  declare module.exports: any;
}

declare module 'babel-plugin-formatjs/visitors/jsx-opening-element' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-formatjs/index' {
  declare module.exports: $Exports<'babel-plugin-formatjs'>;
}
declare module 'babel-plugin-formatjs/index.js' {
  declare module.exports: $Exports<'babel-plugin-formatjs'>;
}
declare module 'babel-plugin-formatjs/types.js' {
  declare module.exports: $Exports<'babel-plugin-formatjs/types'>;
}
declare module 'babel-plugin-formatjs/utils.js' {
  declare module.exports: $Exports<'babel-plugin-formatjs/utils'>;
}
declare module 'babel-plugin-formatjs/visitors/call-expression.js' {
  declare module.exports: $Exports<'babel-plugin-formatjs/visitors/call-expression'>;
}
declare module 'babel-plugin-formatjs/visitors/jsx-opening-element.js' {
  declare module.exports: $Exports<'babel-plugin-formatjs/visitors/jsx-opening-element'>;
}
