// flow-typed signature: 4b1e659b2cc2249ee2a390ffc5f70530
// flow-typed version: <<STUB>>/babel-plugin-react-intl_v^8.2.25/flow_v0.168.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-react-intl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-react-intl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-react-intl/options' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-react-intl/index' {
  declare module.exports: $Exports<'babel-plugin-react-intl'>;
}
declare module 'babel-plugin-react-intl/index.js' {
  declare module.exports: $Exports<'babel-plugin-react-intl'>;
}
declare module 'babel-plugin-react-intl/options.js' {
  declare module.exports: $Exports<'babel-plugin-react-intl/options'>;
}
