// flow-typed signature: 610f677c93dfb38b33be8e71307f030d
// flow-typed version: <<STUB>>/extract-react-intl-messages_v^4.1.1/flow_v0.168.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'extract-react-intl-messages'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'extract-react-intl-messages' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'extract-react-intl-messages/cli' {
  declare module.exports: any;
}

declare module 'extract-react-intl-messages/dist/extract-react-intl' {
  declare module.exports: any;
}

declare module 'extract-react-intl-messages/dist/extract-react-intl/test/test' {
  declare module.exports: any;
}

declare module 'extract-react-intl-messages/dist' {
  declare module.exports: any;
}

declare module 'extract-react-intl-messages/dist/test/json/test' {
  declare module.exports: any;
}

declare module 'extract-react-intl-messages/dist/test/test' {
  declare module.exports: any;
}

declare module 'extract-react-intl-messages/dist/test/yaml/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'extract-react-intl-messages/cli.js' {
  declare module.exports: $Exports<'extract-react-intl-messages/cli'>;
}
declare module 'extract-react-intl-messages/dist/extract-react-intl/index' {
  declare module.exports: $Exports<'extract-react-intl-messages/dist/extract-react-intl'>;
}
declare module 'extract-react-intl-messages/dist/extract-react-intl/index.js' {
  declare module.exports: $Exports<'extract-react-intl-messages/dist/extract-react-intl'>;
}
declare module 'extract-react-intl-messages/dist/extract-react-intl/test/test.js' {
  declare module.exports: $Exports<'extract-react-intl-messages/dist/extract-react-intl/test/test'>;
}
declare module 'extract-react-intl-messages/dist/index' {
  declare module.exports: $Exports<'extract-react-intl-messages/dist'>;
}
declare module 'extract-react-intl-messages/dist/index.js' {
  declare module.exports: $Exports<'extract-react-intl-messages/dist'>;
}
declare module 'extract-react-intl-messages/dist/test/json/test.js' {
  declare module.exports: $Exports<'extract-react-intl-messages/dist/test/json/test'>;
}
declare module 'extract-react-intl-messages/dist/test/test.js' {
  declare module.exports: $Exports<'extract-react-intl-messages/dist/test/test'>;
}
declare module 'extract-react-intl-messages/dist/test/yaml/test.js' {
  declare module.exports: $Exports<'extract-react-intl-messages/dist/test/yaml/test'>;
}
