// flow-typed signature: a425c1a0a14386afbb3960a95a4d2c70
// flow-typed version: <<STUB>>/react-animated-css_v^1.2.1/flow_v0.168.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-animated-css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-animated-css' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-animated-css/lib' {
  declare module.exports: any;
}

declare module 'react-animated-css/lib/prefixer/constants' {
  declare module.exports: any;
}

declare module 'react-animated-css/lib/prefixer' {
  declare module.exports: any;
}

declare module 'react-animated-css/lib/prefixer/prefix' {
  declare module.exports: any;
}

declare module 'react-animated-css/lib/prefixer/supports' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-animated-css/lib/index' {
  declare module.exports: $Exports<'react-animated-css/lib'>;
}
declare module 'react-animated-css/lib/index.js' {
  declare module.exports: $Exports<'react-animated-css/lib'>;
}
declare module 'react-animated-css/lib/prefixer/constants.js' {
  declare module.exports: $Exports<'react-animated-css/lib/prefixer/constants'>;
}
declare module 'react-animated-css/lib/prefixer/index' {
  declare module.exports: $Exports<'react-animated-css/lib/prefixer'>;
}
declare module 'react-animated-css/lib/prefixer/index.js' {
  declare module.exports: $Exports<'react-animated-css/lib/prefixer'>;
}
declare module 'react-animated-css/lib/prefixer/prefix.js' {
  declare module.exports: $Exports<'react-animated-css/lib/prefixer/prefix'>;
}
declare module 'react-animated-css/lib/prefixer/supports.js' {
  declare module.exports: $Exports<'react-animated-css/lib/prefixer/supports'>;
}
