// flow-typed signature: dc174e0e072f59af32b0f8b198243637
// flow-typed version: <<STUB>>/react-toastify_v^8.1.0/flow_v0.168.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-toastify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-toastify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-toastify/dist' {
  declare module.exports: any;
}

declare module 'react-toastify/dist/inject-style.esm' {
  declare module.exports: any;
}

declare module 'react-toastify/dist/inject-style' {
  declare module.exports: any;
}

declare module 'react-toastify/dist/react-toastify.cjs.development' {
  declare module.exports: any;
}

declare module 'react-toastify/dist/react-toastify.cjs.production.min' {
  declare module.exports: any;
}

declare module 'react-toastify/dist/react-toastify.esm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-toastify/dist/index' {
  declare module.exports: $Exports<'react-toastify/dist'>;
}
declare module 'react-toastify/dist/index.js' {
  declare module.exports: $Exports<'react-toastify/dist'>;
}
declare module 'react-toastify/dist/inject-style.esm.js' {
  declare module.exports: $Exports<'react-toastify/dist/inject-style.esm'>;
}
declare module 'react-toastify/dist/inject-style.js' {
  declare module.exports: $Exports<'react-toastify/dist/inject-style'>;
}
declare module 'react-toastify/dist/react-toastify.cjs.development.js' {
  declare module.exports: $Exports<'react-toastify/dist/react-toastify.cjs.development'>;
}
declare module 'react-toastify/dist/react-toastify.cjs.production.min.js' {
  declare module.exports: $Exports<'react-toastify/dist/react-toastify.cjs.production.min'>;
}
declare module 'react-toastify/dist/react-toastify.esm.js' {
  declare module.exports: $Exports<'react-toastify/dist/react-toastify.esm'>;
}
