// flow-typed signature: 9222589ee2212de423ddffe2cb08c82c
// flow-typed version: <<STUB>>/react-intl_v^5.24.0/flow_v0.168.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-intl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-intl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-intl/lib' {
  declare module.exports: any;
}

declare module 'react-intl/lib/src/components/createFormattedComponent' {
  declare module.exports: any;
}

declare module 'react-intl/lib/src/components/dateTimeRange' {
  declare module.exports: any;
}

declare module 'react-intl/lib/src/components/injectIntl' {
  declare module.exports: any;
}

declare module 'react-intl/lib/src/components/message' {
  declare module.exports: any;
}

declare module 'react-intl/lib/src/components/plural' {
  declare module.exports: any;
}

declare module 'react-intl/lib/src/components/provider' {
  declare module.exports: any;
}

declare module 'react-intl/lib/src/components/relative' {
  declare module.exports: any;
}

declare module 'react-intl/lib/src/components/useIntl' {
  declare module.exports: any;
}

declare module 'react-intl/lib/src/types' {
  declare module.exports: any;
}

declare module 'react-intl/lib/src/utils' {
  declare module.exports: any;
}

declare module 'react-intl/react-intl.iife' {
  declare module.exports: any;
}

declare module 'react-intl/src/components/createFormattedComponent' {
  declare module.exports: any;
}

declare module 'react-intl/src/components/dateTimeRange' {
  declare module.exports: any;
}

declare module 'react-intl/src/components/injectIntl' {
  declare module.exports: any;
}

declare module 'react-intl/src/components/message' {
  declare module.exports: any;
}

declare module 'react-intl/src/components/plural' {
  declare module.exports: any;
}

declare module 'react-intl/src/components/provider' {
  declare module.exports: any;
}

declare module 'react-intl/src/components/relative' {
  declare module.exports: any;
}

declare module 'react-intl/src/components/useIntl' {
  declare module.exports: any;
}

declare module 'react-intl/src/types' {
  declare module.exports: any;
}

declare module 'react-intl/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-intl/index' {
  declare module.exports: $Exports<'react-intl'>;
}
declare module 'react-intl/index.js' {
  declare module.exports: $Exports<'react-intl'>;
}
declare module 'react-intl/lib/index' {
  declare module.exports: $Exports<'react-intl/lib'>;
}
declare module 'react-intl/lib/index.js' {
  declare module.exports: $Exports<'react-intl/lib'>;
}
declare module 'react-intl/lib/src/components/createFormattedComponent.js' {
  declare module.exports: $Exports<'react-intl/lib/src/components/createFormattedComponent'>;
}
declare module 'react-intl/lib/src/components/dateTimeRange.js' {
  declare module.exports: $Exports<'react-intl/lib/src/components/dateTimeRange'>;
}
declare module 'react-intl/lib/src/components/injectIntl.js' {
  declare module.exports: $Exports<'react-intl/lib/src/components/injectIntl'>;
}
declare module 'react-intl/lib/src/components/message.js' {
  declare module.exports: $Exports<'react-intl/lib/src/components/message'>;
}
declare module 'react-intl/lib/src/components/plural.js' {
  declare module.exports: $Exports<'react-intl/lib/src/components/plural'>;
}
declare module 'react-intl/lib/src/components/provider.js' {
  declare module.exports: $Exports<'react-intl/lib/src/components/provider'>;
}
declare module 'react-intl/lib/src/components/relative.js' {
  declare module.exports: $Exports<'react-intl/lib/src/components/relative'>;
}
declare module 'react-intl/lib/src/components/useIntl.js' {
  declare module.exports: $Exports<'react-intl/lib/src/components/useIntl'>;
}
declare module 'react-intl/lib/src/types.js' {
  declare module.exports: $Exports<'react-intl/lib/src/types'>;
}
declare module 'react-intl/lib/src/utils.js' {
  declare module.exports: $Exports<'react-intl/lib/src/utils'>;
}
declare module 'react-intl/react-intl.iife.js' {
  declare module.exports: $Exports<'react-intl/react-intl.iife'>;
}
declare module 'react-intl/src/components/createFormattedComponent.js' {
  declare module.exports: $Exports<'react-intl/src/components/createFormattedComponent'>;
}
declare module 'react-intl/src/components/dateTimeRange.js' {
  declare module.exports: $Exports<'react-intl/src/components/dateTimeRange'>;
}
declare module 'react-intl/src/components/injectIntl.js' {
  declare module.exports: $Exports<'react-intl/src/components/injectIntl'>;
}
declare module 'react-intl/src/components/message.js' {
  declare module.exports: $Exports<'react-intl/src/components/message'>;
}
declare module 'react-intl/src/components/plural.js' {
  declare module.exports: $Exports<'react-intl/src/components/plural'>;
}
declare module 'react-intl/src/components/provider.js' {
  declare module.exports: $Exports<'react-intl/src/components/provider'>;
}
declare module 'react-intl/src/components/relative.js' {
  declare module.exports: $Exports<'react-intl/src/components/relative'>;
}
declare module 'react-intl/src/components/useIntl.js' {
  declare module.exports: $Exports<'react-intl/src/components/useIntl'>;
}
declare module 'react-intl/src/types.js' {
  declare module.exports: $Exports<'react-intl/src/types'>;
}
declare module 'react-intl/src/utils.js' {
  declare module.exports: $Exports<'react-intl/src/utils'>;
}
