// flow-typed signature: 884351339fbab8211eff7e93bb44ff45
// flow-typed version: <<STUB>>/styled-react-modal_v^2.1.0/flow_v0.168.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styled-react-modal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styled-react-modal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'styled-react-modal/build' {
  declare module.exports: any;
}

declare module 'styled-react-modal/examples/fancyModal' {
  declare module.exports: any;
}

declare module 'styled-react-modal/src/baseStyles' {
  declare module.exports: any;
}

declare module 'styled-react-modal/src/context' {
  declare module.exports: any;
}

declare module 'styled-react-modal/src' {
  declare module.exports: any;
}

declare module 'styled-react-modal/src/Modal' {
  declare module.exports: any;
}

declare module 'styled-react-modal/src/ModalProvider' {
  declare module.exports: any;
}

declare module 'styled-react-modal/tests/Modal.test' {
  declare module.exports: any;
}

declare module 'styled-react-modal/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'styled-react-modal/build/index' {
  declare module.exports: $Exports<'styled-react-modal/build'>;
}
declare module 'styled-react-modal/build/index.js' {
  declare module.exports: $Exports<'styled-react-modal/build'>;
}
declare module 'styled-react-modal/examples/fancyModal.jsx' {
  declare module.exports: $Exports<'styled-react-modal/examples/fancyModal'>;
}
declare module 'styled-react-modal/src/baseStyles.jsx' {
  declare module.exports: $Exports<'styled-react-modal/src/baseStyles'>;
}
declare module 'styled-react-modal/src/context.jsx' {
  declare module.exports: $Exports<'styled-react-modal/src/context'>;
}
declare module 'styled-react-modal/src/index' {
  declare module.exports: $Exports<'styled-react-modal/src'>;
}
declare module 'styled-react-modal/src/index.jsx' {
  declare module.exports: $Exports<'styled-react-modal/src'>;
}
declare module 'styled-react-modal/src/Modal.jsx' {
  declare module.exports: $Exports<'styled-react-modal/src/Modal'>;
}
declare module 'styled-react-modal/src/ModalProvider.jsx' {
  declare module.exports: $Exports<'styled-react-modal/src/ModalProvider'>;
}
declare module 'styled-react-modal/tests/Modal.test.jsx' {
  declare module.exports: $Exports<'styled-react-modal/tests/Modal.test'>;
}
declare module 'styled-react-modal/webpack.config.js' {
  declare module.exports: $Exports<'styled-react-modal/webpack.config'>;
}
